// apps/web/src/routes/login/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { authApi } from '$lib/apis/auth';
	import logo from '$lib/assets/images/logo.svg';
	import Button from '$lib/components/ui/button/button.svelte';
	import { setToken } from '$lib/services/storage';
	import { loginSchema } from '$lib/utils/schema';
	import { useMutation } from '@sveltestack/svelte-query';
	import { superForm, superValidateSync } from 'sveltekit-superforms/client';

	const loginMutate = useMutation(authApi.login);

	const { form, errors, constraints, enhance } = superForm(superValidateSync(loginSchema), {
		SPA: true,
		validators: loginSchema,
		taintedMessage: false,
		onUpdate: async ({ form }) => {
			if (form.valid) {
				const { data } = await $loginMutate.mutateAsync(form.data);
				if (data.token) {
					goto('/');
					setToken(data.token);
				}
			}
		}
	});
</script>

<div class="flex w-full items-center justify-center">
	<div class="flex flex-col items-center">
		<img src={logo} alt="logo" class="w-20" />
		<h1 class="my-11 text-4xl">Connect with your favourite people</h1>
		<form method="POST" class="flex w-80 flex-col items-center" use:enhance>
			<input
				class="input"
				placeholder="Email address"
				bind:value={$form.email}
				{...$constraints.email}
			/>
			{#if $errors.email}<span class="mt-1 w-full text-red-500">{$errors.email}</span>{/if}
			<input
				class="input mt-3"
				type="password"
				placeholder="Password"
				bind:value={$form.password}
				{...$constraints.password}
			/>
			{#if $errors.password}<span class="mt-1 w-full text-red-500">{$errors.password}</span>{/if}
			<a href="/signup" class="hover:text-blue my-6 underline">Create new account</a>

			<Button class="btn w-fit rounded-full" type="submit">Continue</Button>
		</form>
	</div>
</div>

// apps/facebook-web/pages/login.vue
<script setup lang="ts">
  import { loginSchema } from '~/lib/schema'
  import { request } from '~/lib/request'
  import { configure } from 'vee-validate';
  import type { z } from 'zod';
  import { setToken } from '~/lib/storage';

  definePageMeta({
      middleware: 'auth'
  });
  const router = useRouter()

  const { mutateAsync } = useMutation({
    mutationFn: (data: z.infer<typeof loginSchema>) => request.post('/sign-in', data),
  })

  configure({
    validateOnBlur: true
  })

  const { handleSubmit, errors, useFieldModel } = useForm({
    validationSchema: toTypedSchema(loginSchema),
  })

  const [email, password] = useFieldModel(['email', 'password']);

  const onSubmit = handleSubmit(async (values) => {
    const res = await mutateAsync(values)
    setToken(res.data.token)
    router.push('/')
  })
</script>

<template>
  <div class="bg-gray-200 h-screen">
    <div class="max-w-5xl w-full mx-auto flex justify-between items-center h-screen">
      <div class="w-1/2">
        <h1 class="text-primary text-6xl font-bold">facebook</h1>
        <p class="text-3xl mt-4">Facebook helps you connect and share with the people in your life.</p>
      </div>
      <form class="p-4 bg-white rounded-xl w-104 h-fit" @submit="onSubmit">
        <Input placeholder="Email address or phone number" v-model="email" />
        <span class="mt-1 w-full text-red-500">{{ errors.email }}</span>
        <Input placeholder="Password" class="my-3" v-model="password" type="password" />
        <span class="mt-1 w-full text-red-500">{{ errors.password }}</span>
        <Button class="w-full text-xl" type="submit">Log in</Button>
        <a class="text-primary hover:underline mt-3 block text-center"> Forgotten password? </a>
        <hr class="my-4" />
        <Button variant="success" class="w-full text-xl my-2" type="button">Create new account</Button>
      </form>
    </div>
  </div>
</template>
